spring:
  kafka:
    bootstrap-servers: 150.158.122.249:9092
    #
    consumer:
      client-id: CLIENT_ID_01
      group-id: group1
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      #ack-mode: manual_immediate